### ISSUE TITLE
您好，看了您的论文，有个地方不太明白。关于正交矩阵那里。

### ISSUE THREAD

**Issue by Atseini** [lpworld/DDTCDR#1]
![image](https://wx4.sinaimg.cn/mw690/005TAG8Cgy1gjw56mcuu1j30zy0dxq4v.jpg)

上图中两个域使用同一个正交矩阵来进行知识迁移，但是在您的代码实现中，如下
```python
orth_loss_A, orth_loss_B = torch.zeros(1), torch.zeros(1)
reg = 1e-6
for name, param in self.modelA.bridge.named_parameters():
      if 'bias' not in name:
      param_flat = param.view(param.shape[0], -1)
      sym = torch.mm(param_flat, torch.t(param_flat))
      sym -= torch.eye(param_flat.shape[0])
      orth_loss_A = orth_loss_A + (reg * sym.abs().sum())
orth_loss_A.backward()
for name, param in self.modelB.bridge.named_parameters():
      if 'bias' not in name:
       param_flat = param.view(param.shape[0], -1)
       sym = torch.mm(param_flat, torch.t(param_flat))
       sym -= torch.eye(param_flat.shape[0])
       orth_loss_B = orth_loss_B + (reg * sym.abs().sum())
orth_loss_B.backward()
```
问题：
1. 对modelA和modelB的两个`self.bridge`都进行了训练，这里的区别是什么？是否与论文的描述不一致？
2. 在计算正交损失过程中，您减去torch.eye的含义是什么？

刚刚入门的新人，望解答，非常感谢！

**Comment by lpworld** [comment]
你好，进行知识迁移的确实是同一个矩阵。从A->B是X，从B->A是X^T。如果你把这里对modelB的self.bridge去掉就会和文章里介绍的一样，这里都加上是为了加速收敛（因为在开始的时候我们就做了正交化约束）。减去torch.eye是为了防止矩阵出现不满秩的情况出现，所以人为的加进去一些扰动（比如极端情况下sym可能为空矩阵）。感谢你对文章的关注！

**Comment by Atseini** [comment]
> 你好，进行知识迁移的确实是同一个矩阵。从A->B是X，从B->A是X^T。如果你把这里对modelB的self.bridge去掉就会和文章里介绍的一样，这里都加上是为了加速收敛（因为在开始的时候我们就做了正交化约束）。减去torch.eye是为了防止矩阵出现不满秩的情况出现，所以人为的加进去一些扰动（比如极端情况下sym可能为空矩阵）。感谢你对文章的关注！

谢谢您的回答，您说的`对modelB的self.bridge去掉就会和文章里介绍的一样`我还是有点没懂。
```python
book_ratings_pred1 = self.modelA(book_user_embeddings, book_item_embeddings)
lossA1 = self.crit(book_ratings_pred1.squeeze(1), book_rating)
book_ratings_pred2 = self.modelB(book_user_embeddings, book_item_embeddings, dual=True)
lossA2 = self.crit(book_ratings_pred2.squeeze(1), book_rating)
movie_ratings_pred1 = self.modelB(movie_user_embeddings, movie_item_embeddings)
lossB1 = self.crit(movie_ratings_pred1.squeeze(1), movie_rating)
movie_ratings_pred2 = self.modelA(movie_user_embeddings, movie_item_embeddings, dual=True)
lossB2 = self.crit(movie_ratings_pred2.squeeze(1), movie_rating)
```
原代码按我的理解，`book_ratings_pred2` 是对应公式中 `RS_B(X*W_uA, W_iA)`,`movie_ratings_pred2`对应公式中`RS_A(X^T*W_uB, W_iB)`。但是按照代码的意思X和X^T两个分别对应的modelA.bridge和modelB.bridge.我的理解就是modelA.bridge和modelB.bridge是两个模型单独的变量。你说是一个矩阵进行迁移我有点困扰。烦请在做解答:sweat_smile:

**Comment by lpworld** [comment]
你说的没错呀。这里我给出的代码相当于是用X和Y两个矩阵同时去做正交迁移学习，如果你把modelB的bridge去掉 那就只有一个X矩阵，也就是文章里所说的情况了。你可以自己去修改一下，两种方法的结果很接近，这种收敛的会快一点。

**Comment by Atseini** [comment]
噢噢，好的，再次谢谢您:smile:
