### ISSUE TITLE
关于代码和示例数据的请教

### ISSUE THREAD

**Issue by Jaccelerator** [lpworld/DDTCDR#3]
您好，非常感谢您如此清晰且精妙的想法和实现，我受益良多。关于代码上，我有两点疑问，还望不吝赐教。

1. 论文里说了 alpha 的作用时是："α =0 or there is no user overlap between two domains, the dual learning model degenerates to two separate single-domain recommendation models"，同时在 4.1 节数据描述中也说了：" three domains being linked together through a common user ID identifying the same user"。但是您给出的示例数据中，movie 中存在 book 域中没有的 user（其中 movie 总 user num 2007，book 总 user num 1005），此时为这些 non-overlap 的 user，也可以应用 bridge 并将最终的 prediction score 以 alpha 结合，是这样吗？

2. 代码中只有训练过程中用到了 bridge 映射和 alpha 结合两个单域 NCF 输出（论文中给出的 prediction，但代码中给出的是 loss），推理测试阶段只使用了单域模型 NCF。如果是 loss 结合，那推理阶段需不需要对 prediction score 进行结合了呢？

https://github.com/lpworld/DDTCDR/blob/e71e458d3e741872f4d3ba5dcebc92f23f47e4ec/engine.py#L43-L44

https://github.com/lpworld/DDTCDR/blob/e71e458d3e741872f4d3ba5dcebc92f23f47e4ec/engine.py#L112-L115

**Comment by lpworld** [comment]
您好！感谢你对文章的关注。第一个问题，当alpha为0的时候仍然可以把non-overlap user应用到bridge但他们不会影响最后的preidction score。第二个问题，在推理阶段我们当时的想法是实际业务场景里从不同的数据源传输数据代价很高，所以只采用了单域进行预测。我们一些后续的工作也尝试了一些其他的做法，可以参考DML （https://ieeexplore.ieee.org/iel7/69/9973432/09409658.pdf）和DASL （https://dl.acm.org/doi/abs/10.1145/3447548.3467140）这两篇文章。

**Comment by Jaccelerator** [comment]
非常感谢您及时的回复。第一个问题还是不太懂，如果有 non-overlap 用户，同时 alpha 也不为 0，此时也应该用 bridge 映射并计算映射到对面领域后的推荐 loss 吗（看代码中应该是这样的，但是从论文中感觉得是 overlap 用户）？

**Comment by lpworld** [comment]
是的，bridge映射只作用于overlap用户。这里的代码只是一个示范，实际数据集里你可能需要先把overlap用户找出来。

**Comment by Jaccelerator** [comment]
好的，感谢老师的回复。祝老师新年快乐！
